title: Yzy的毕生所学
description: 日拱一卒 功不唐捐
remote_theme: just-the-docs/just-the-docs

url: "https://yzy-2006.github.io"
baseurl: ""

search_enabled: true

aux_links:
  GitHub 仓库: https://github.com/Yzy-2006/yzy-2006.github.io

nav_sort: case_insensitive

heading_anchors: true

color_scheme: light

plugins:
  - jekyll-remote-theme
